### PR TITLE
Windows 10 make

### PR DESCRIPTION
**Pull request by Alex079**

### CODE REVIEW

**Comment by Alex079** [comment]
this should fix #11

**Comment by Alex079** [comment]
should address part of #13

**Comment by Alex079** [comment]
9066502ed3b21fe68ebd79f21082da94dea35b33 should address #7, #8 and #11 at least partially.

**Comment by Prow7** [comment]
I just got caught by the case insensitive .C wildcards bug for Windows builds. It will be nice to have.

**Comment by Alex079** [comment]
Ideally, the version from this branch should solve most if not all of the problems reported so far.
Two things left to be done here before release:
- print build progress nicely
- set sensible default configuration options

**Comment by Alex079** [comment]
#15 should be addressed in this PR

**Pull request merged**
